tunnel: dev-mt
credentials-file: .cloudflared/creds.json

originRequest:
  httpHostHeader: localhost

ingress:
  - hostname: dev-mt.mrz.sh
    service: http://localhost:8080
  - service: http_status:404
